apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus
    app.kubernetes.io/part-of: load-app-9c397d35-bfd2-407f-81ae-bb606d4356f5
  name: devfile-sample-code-with-w6yu
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-code-with-quarkus
    weight: null
status: {}
